/** Display names for ProjectViewer nav bar - must match project branding */
export const PROJECT_DISPLAY_NAMES = {
  "shophube": "ShopHub",
  "styleverse": "Styleverse",
  "royal-palace": "Royal Palace",
  "prestigra-den": "Prestigra Den",
  "paradise-resort": "Paradise Resort Bali",
  "indian-resort": "Indian Resort",
  "caremax": "Caremax",
  "foodswift": "FoodSwift",
  "foodhub": "FoodHub",
  "healthcare-portal": "Healthcare Portal",
  "medicare-plus": "Medicare Plus",
  "eduflow": "EduFlow",
  "velomynt-realestate": "Velomynt",
  "tours": "Tours",
  "finflow": "FinFlow",
  "logiflow": "LogiFlow",
  "premier-estate": "PremierEstate",
  "quickserve": "QuickServe",
  "luxury-salon": "Luxe Beauty Studio",
};

export const PROJECT_MAP = {
  "shophube": "/All_projects/shophube/dist/index.html",
  "styleverse": "/All_projects/Styleverse/index.html",
  "royal-palace": "/All_projects/Royal_palace/index.html",
  "prestigra-den": "/All_projects/prestigegrand/index.html",
  "paradise-resort": "/All_projects/paradiseresort/index.html",
  "indian-resort": "/All_projects/Indianresort/index.html",
  "caremax": "/All_projects/caremahospital/dist/index.html",
  "foodswift": "/All_projects/fooddelivery/index.html",
  "foodhub": "/All_projects/foodhub/index.html",
  "healthcare-portal": "/All_projects/Medicare/index.html",
  "medicare-plus": "/All_projects/MedicareHealthcare_Clinic/index.html",
  "eduflow": "/All_projects/Equcation/index.html",
  "velomynt-realestate": "/All_projects/Demo1/index.html",
  "tours": "/All_projects/tours/index.html",
  "finflow": "/All_projects/Finflow/index.html",
  "logiflow": "/All_projects/Logiflow/index.html",
  "premier-estate": "/All_projects/PremierEstate/index.html",
  "quickserve": "/All_projects/quickServe/index.html",
  "luxury-salon": "/All_projects/LuxurySalonWebsite/index.html",
};
